# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hamid/workspace/ucjwt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hamid/workspace/ucjwt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hamid/workspace/ucjwt/CMakeFiles /home/hamid/workspace/ucjwt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hamid/workspace/ucjwt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Main

# Build rule for target.
Main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Main
.PHONY : Main

# fast build rule for target.
Main/fast:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/build
.PHONY : Main/fast

base64.o: base64.c.o

.PHONY : base64.o

# target to build an object file
base64.c.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/base64.c.o
.PHONY : base64.c.o

base64.i: base64.c.i

.PHONY : base64.i

# target to preprocess a source file
base64.c.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/base64.c.i
.PHONY : base64.c.i

base64.s: base64.c.s

.PHONY : base64.s

# target to generate assembly for a file
base64.c.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/base64.c.s
.PHONY : base64.c.s

hmac-sha256.o: hmac-sha256.c.o

.PHONY : hmac-sha256.o

# target to build an object file
hmac-sha256.c.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/hmac-sha256.c.o
.PHONY : hmac-sha256.c.o

hmac-sha256.i: hmac-sha256.c.i

.PHONY : hmac-sha256.i

# target to preprocess a source file
hmac-sha256.c.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/hmac-sha256.c.i
.PHONY : hmac-sha256.c.i

hmac-sha256.s: hmac-sha256.c.s

.PHONY : hmac-sha256.s

# target to generate assembly for a file
hmac-sha256.c.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/hmac-sha256.c.s
.PHONY : hmac-sha256.c.s

jwt.o: jwt.c.o

.PHONY : jwt.o

# target to build an object file
jwt.c.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/jwt.c.o
.PHONY : jwt.c.o

jwt.i: jwt.c.i

.PHONY : jwt.i

# target to preprocess a source file
jwt.c.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/jwt.c.i
.PHONY : jwt.c.i

jwt.s: jwt.c.s

.PHONY : jwt.s

# target to generate assembly for a file
jwt.c.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/jwt.c.s
.PHONY : jwt.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main.c.s
.PHONY : main.c.s

sha256.o: sha256.c.o

.PHONY : sha256.o

# target to build an object file
sha256.c.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/sha256.c.o
.PHONY : sha256.c.o

sha256.i: sha256.c.i

.PHONY : sha256.i

# target to preprocess a source file
sha256.c.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/sha256.c.i
.PHONY : sha256.c.i

sha256.s: sha256.c.s

.PHONY : sha256.s

# target to generate assembly for a file
sha256.c.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/sha256.c.s
.PHONY : sha256.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Main"
	@echo "... base64.o"
	@echo "... base64.i"
	@echo "... base64.s"
	@echo "... hmac-sha256.o"
	@echo "... hmac-sha256.i"
	@echo "... hmac-sha256.s"
	@echo "... jwt.o"
	@echo "... jwt.i"
	@echo "... jwt.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sha256.o"
	@echo "... sha256.i"
	@echo "... sha256.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

